AUTH_KEY = "auth_secret"  # REPLACE WITH SECRET KEY FOR FIRST LOGIN
USERNAME = "test@gmail.com"  # SET STATIC USERNAME YOU WANT OR SET IT AS EMPTY STRING
EMAIL_ID = "test.tech@gmail.com"  # EMAIL ID FOR MAIL SEND
EMAIL_PASS = "xxxxxxxxxxxxxxxx"  # SERVICE PROVIDE MAIL ID USE GMAIL ONLY
SECRET_KEY = "secret"  # SECRET AUTH KEY FOR OPENING AND SENDING PASSWORD LIST TO MAIL
